### ISSUE TITLE
how to load the json file

### ISSUE THREAD

**Issue by DarkArtistry** [LuisMPS/build-ui#1]
**How to understand the saved json file / how to load the json file**

- Section: Tutorial

### Suggest New Content

As the json tree is very verbose / maybe a section on how the saved data can be loaded?

I see that in the demo folder you have a useExporter utility function that generates a full html page document.

may i suggest to work on another utility function that exports the page as only a single page instead of a full html document?

**Comment by LuisMPS** [comment]
Hi Dark,
Thanks for your suggestion.

Just let me try to understand what you are asking for here.
Having a json file containing the tree structure of a page, you want a way to load it back and put back all the elements that were saved on the file. If that is what you mean, you can probably go check out the demo, try saving a page and load it back with the buttons on the menu. Main code for that can be found here: 
https://github.com/LuisMPS/build-ui/blob/main/examples/demo/src/components/MenuBar.js

I also just realised it is not exactly working as it should (you can still get it to work), and just spotted the error and will fix as soon as possible. Hope you can get a good idea on how to do this though. 

I'm just making an assumption, but if that's not what you mean, let me know!!

**Comment by DarkArtistry** [comment]
you answered the question. Thank you i will take a look at MenuBar.js !

**Comment by maikishore** [comment]
How can we preview or publish the built site?

**Comment by LuisMPS** [comment]
Hi. I'll close this issue. The error I commented about was fixed. Thanks.
